# Generated by Django 5.0.7 on 2024-07-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloquesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, verbose_name='NombreBloque')),
            ],
            options={
                'verbose_name': 'bloque',
                'verbose_name_plural': 'bloques',
                'db_table': 'bloques',
            },
        ),
        migrations.CreateModel(
            name='CamarasDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=80, verbose_name='NombreUsuario')),
                ('passwords', models.CharField(max_length=20, verbose_name='password')),
                ('ip_camara', models.GenericIPAddressField(verbose_name='IP Camara')),
                ('puerto', models.CharField(max_length=15, verbose_name='puerto')),
            ],
            options={
                'verbose_name': 'camara',
                'verbose_name_plural': 'camaras',
                'db_table': 'camaras',
            },
        ),
        migrations.CreateModel(
            name='RolesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='NombreRol')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='AmbientesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='NombreAmbiente')),
                ('bloque_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.bloquesdb')),
            ],
            options={
                'verbose_name': 'ambiente',
                'verbose_name_plural': 'ambientes',
                'db_table': 'ambientes',
            },
        ),
    ]
