# Generated by Django 5.0.7 on 2024-08-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camarasdb_ambiente_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camarasdb',
            name='ambiente_fk',
        ),
        migrations.DeleteModel(
            name='AmbientesDB',
        ),
    ]
