# Generated by Django 5.0.7 on 2024-08-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_remove_camarasdb_ambiente_fk_delete_ambientesdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloquesDB',
        ),
    ]
